const fs = require('fs');
const path = require('path');

const envFile = fs.readFileSync(path.join(process.cwd(), '.env'), 'utf8');
envFile.split('\n').forEach(line => {
  const eqIndex = line.indexOf('=');
  if (eqIndex > 0) {
    const key = line.slice(0, eqIndex).trim();
    const val = line.slice(eqIndex + 1).trim();
    if (key && !key.startsWith('#')) process.env[key] = val;
  }
});
// Suppress Octokit request logging
process.env.NODE_DEBUG = '';

const { createMessage, MESSAGE_TYPES, PRIORITY_LEVELS, TIERS, AGENTS } = require('../../contracts/base');
const { createBotClient, postToChannel, waitForApproval } = require('../../discord/client');
const { Octokit } = require('@octokit/rest');

/**
 * PM Agent — ephemeral, spawned per project.
 * Responsible for:
 * - Reading estimation history
 * - Building cost estimates
 * - Creating GitHub Issues from spec deliverables
 * - Setting up Discord project channels
 * - Managing the project backlog
 */

class PMAgent {
  constructor(spec, projectChannels) {
    this.spec = spec;
    this.projectChannels = projectChannels;
    this.client = createBotClient(process.env.PM_TOKEN);
    this.octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
    this.owner = process.env.GITHUB_OWNER;
    this.repo = process.env.GITHUB_REPO;
    this.ollamaUrl = process.env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434';
    this.model = process.env.MANAGER_MODEL || 'llama3.1:8b';
    this.projectRepo = null;

    this.ready = new Promise((resolve) => {
      this.client.once('clientReady', () => {
        console.log(`[PM] Online as ${this.client.user.tag}`);
        resolve();
      });
    });
  }

  /**
   * Main entry point — runs the full PM setup sequence.
   */
  async run() {
    await this.ready;
    await this.postToManagers(`📋 PM Agent online for project: **${this.spec.projectName}**`);

    try {
      const history = this.readEstimationHistory();
      const estimate = await this.buildEstimate(history);
      const approved = await this.requestEstimateApproval(estimate);

      if (!approved) {
        await this.postToManagers(`❌ Cost estimate rejected. Awaiting revised spec from Director.`);
        return;
      }

      const projectRepo = await this.createProjectRepo();
      this.projectRepo = projectRepo;

      await this.setupGitHubLabels();

      console.log('[PM] Creating Issues...');
      await this.createIssues();
      console.log('[PM] Issues created.');

      await this.postToManagers(`✅ Project setup complete. Issues created. Workers can begin.`);

    } catch (err) {
      console.error('[PM] Fatal error in run():', err.message);
      console.error(err.stack);
    }
  }

  /**
   * Creates a new GitHub repo for the project.
   * @returns {object} projectRepo
   */
  async createProjectRepo() {
    const repoName = this.spec.projectName;

    try {
      const { data: repo } = await this.octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: `Generated by agent-dev-team — ${this.spec.brief.desiredOutcome}`,
        private: false,
        auto_init: true
      });

      console.log(`[PM] Project repo created: ${repo.html_url}`);
      await this.postToManagers(`📦 Project repo created: ${repo.html_url}`);

      return {
        owner: repo.owner.login,
        repo: repo.name,
        url: repo.html_url,
        defaultBranch: repo.default_branch
      };

    } catch (err) {
      if (err.status === 422) {
        console.log(`[PM] Repo already exists: ${repoName}`);
        const { data: repo } = await this.octokit.repos.get({
          owner: this.owner,
          repo: repoName
        });
        return {
          owner: repo.owner.login,
          repo: repo.name,
          url: repo.html_url,
          defaultBranch: repo.default_branch
        };
      }
      throw err;
    }
  }

  /**
   * Reads the estimation history from the repo.
   * @returns {object} history
   */
  readEstimationHistory() {
    const historyPath = path.join(process.cwd(), 'projects', 'estimation-history.json');
    if (!fs.existsSync(historyPath)) {
      return { projects: [] };
    }
    return JSON.parse(fs.readFileSync(historyPath, 'utf8'));
  }

  /**
   * Builds a cost estimate using the local model and estimation history.
   * @param {object} history
   * @returns {object} estimate
   */
  async buildEstimate(history) {
    const relevantHistory = history.projects
      .filter(p => p.projectType === this.spec.projectType)
      .slice(-5);

    const hoursResponse = await fetch(`${this.ollamaUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: this.model,
        prompt: `You are a project manager. Given this project: "${this.spec.projectName}" with ${this.spec.deliverables?.length || 1} deliverables, estimate total development hours. Respond with ONLY a single number between 1 and 100. No other text.`,
        stream: false
      })
    });

    const hoursData = await hoursResponse.json();
    const hours = parseInt(hoursData.response.trim().match(/\d+/)?.[0] || '8');
    const cost = hours * 20;

    return {
      hours,
      cost,
      currency: process.env.CURRENCY || 'CAD',
      breakdown: this.spec.deliverables?.map(d => ({
        task: d.name,
        hours: Math.ceil(hours / (this.spec.deliverables.length || 1)),
        cost: Math.ceil(cost / (this.spec.deliverables.length || 1))
      })) || [],
      confidence: relevantHistory.length > 0 ? 'medium' : 'low',
      notes: relevantHistory.length > 0 ? `Based on ${relevantHistory.length} similar projects` : 'No historical data available'
    };
  }

  /**
   * Posts estimate to #approvals and waits for executive confirmation.
   * @param {object} estimate
   * @returns {boolean} approved
   */
  async requestEstimateApproval(estimate) {
    const approvalsChannel = process.env.DISCORD_CHANNEL_APPROVALS;
    const estimateJson = JSON.stringify(estimate, null, 2);

    const approvalMessage = await this.client.channels
      .fetch(approvalsChannel)
      .then(channel => channel.send(
        `**Cost Estimate — ${this.spec.projectName}**\n\n` +
        `**Total:** ${estimate.cost} ${estimate.currency}\n` +
        `**Hours:** ${estimate.hours}\n` +
        `**Confidence:** ${estimate.confidence}\n\n` +
        `\`\`\`json\n${estimateJson}\n\`\`\`\n\n` +
        `Type \`approve\` to confirm or \`reject\` to decline.`
      ));

    try {
      return await waitForApproval(this.client, approvalMessage.id, approvalsChannel);
    } catch (err) {
      await postToChannel(
        this.client,
        process.env.DISCORD_CHANNEL_ALERTS,
        `⚠️ Cost estimate approval timed out for: ${this.spec.projectName}`
      );
      return false;
    }
  }

  /**
   * Sets up GitHub labels for this project in the agent-dev-team repo.
   */
  async setupGitHubLabels() {
    const labels = [
      { name: `project:${this.spec.projectName}`, color: '0075ca' },
      { name: 'tier:worker', color: 'e4e669' },
      { name: 'tier:manager', color: 'f9d0c4' },
      { name: 'status:backlog', color: 'd93f0b' },
      { name: 'status:in-progress', color: '0052cc' },
      { name: 'status:review', color: 'bfd4f2' },
      { name: 'status:complete', color: '0e8a16' },
      { name: 'status:blocked', color: 'b60205' },
      { name: 'priority:high', color: 'e11d48' },
      { name: 'priority:medium', color: 'f97316' },
      { name: 'priority:low', color: '84cc16' },
    ];

    for (const label of labels) {
      try {
        await this.octokit.issues.createLabel({
          owner: this.owner,
          repo: this.repo,
          name: label.name,
          color: label.color
        });
      } catch (err) {
        if (err.status !== 422) console.error(`[PM] Label error: ${err.message}`);
      }
    }

    await this.postToManagers(`🏷️ GitHub labels created for project: ${this.spec.projectName}`);
  }

  /**
   * Creates GitHub Issues from spec deliverables in the agent-dev-team repo.
   * Each Issue is a complete, self-contained task brief for a worker.
   */
  async createIssues() {
    const { deliverables, projectName, architecture } = this.spec;

    for (const deliverable of deliverables) {
      const body = `## Task Brief

**Project:** ${projectName}
**Project Repo:** ${this.projectRepo?.url || 'TBD'}
**Type:** ${deliverable.type}

## Objective
${deliverable.description}

## Tech Stack
- Language: ${architecture.techStack.language}
- Runtime: ${architecture.techStack.runtime}
- Packages: ${architecture.techStack.packages.join(', ') || 'none'}

## Acceptance Criteria
${deliverable.acceptanceCriteria.map(c => `- [ ] ${c}`).join('\n')}

## Instructions
- Work in the project repo: ${this.projectRepo?.url || 'TBD'}
- Create a branch: \`coder/[issue-number]/${deliverable.name}\`
- Complete all acceptance criteria
- Open a PR when done
- Do not ask for clarification — use your best judgment

## Context
${JSON.stringify(architecture, null, 2)}`;

      const issue = await this.octokit.issues.create({
        owner: this.owner,
        repo: this.repo,
        title: `[${projectName}] ${deliverable.name}`,
        body,
        labels: [
          `project:${projectName}`,
          'tier:worker',
          'status:backlog',
          'priority:medium'
        ]
      });

      await this.postToManagers(`📌 Issue created: #${issue.data.number} — ${deliverable.name}`);
    }
  }

  /**
   * Posts a message to the project's #managers channel.
   * @param {string} content
   */
  async postToManagers(content) {
    await postToChannel(this.client, this.projectChannels.managers, content);
  }

  /**
   * Discards this PM agent — called when project closes.
   */
  async discard() {
    console.log(`[PM] Discarding for project: ${this.spec.projectName}`);
    await this.client.destroy();
  }
}

module.exports = PMAgent;